AWSTemplateFormatVersion: "2010-09-09"
Resources: 

  JITPRole: 

    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "iot.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSIoTLogging
        - arn:aws:iam::aws:policy/service-role/AWSIoTRuleActions
        - arn:aws:iam::aws:policy/service-role/AWSIoTThingsRegistration


Outputs:
  JITPRoleName:
    Description: Role name for just-in-time-provisioning (JITP) of devices to IoT COre
    Value: !Ref JITPRole
  JITPRoleArn:
    Description: Role ARN for just-in-time-provisioning (JITP) of devices to IoT COre
    Value: !GetAtt JITPRole.Arn
  